server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://laurenfrost.tk:5432/lyosha
    username: auth
    password:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: hinfantry2
    password:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true


security:
  jwt:
    secret: mySecretKey
    keypass:
    jks-file: jwt.jks
    key-alias: jwtkey